//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module rv32i_fpga(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// LED //////////
output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// LCD //////////
	output		          		LCD_BLON,
	inout 		     [7:0]		LCD_DATA,
	output		          		LCD_EN,
	output		          		LCD_ON,
	output		          		LCD_RS,
	output		          		LCD_RW,

	//////////// PS2 for Keyboard and Mouse //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// VGA //////////
	output		     [7:0]		VGA_B,
	output		          		VGA_BLANK_N,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS

);

//=======================================================
//  REG/WIRE declarations
//=======================================================

wire        clk;
wire        rst;

wire [31:0] imemDataOut;
wire [31:0] imemAddr;

wire [31:0] dmemDataOut;
wire [31:0] dmemDataIn;
wire [31:0] dmemAddr;
wire [2:0]  dmemOp;
wire        dmemWe;

// Raw RAM-side data signals
wire [31:0] dmemRawOut;
wire [31:0] dmemRamOut;
wire [31:0] dmemMmioOut;
wire [31:0] dmemLcdOut;
wire [31:0] dmemKbdOut;
wire [31:0] dmemVgaOut;
wire [31:0] dmemVgaTextOut;
wire [31:0] dmemRamIn;
wire [3:0]  dmemByteEn;
wire [14:0] dmemRdAddr;
wire [14:0] dmemWrAddr;
wire        dmemRamWe;
wire        dmemMmioHit;
wire        dmemLcdHit;
wire        dmemKbdHit;
wire        dmemVgaHit;
wire        dmemVgaTextHit;
wire        vgaTextWe;
wire [11:0] vgaTextAddrA;
wire [11:0] vgaTextAddrB;
wire [7:0]  vgaTextInA;
wire [7:0]  vgaTextOutA;
wire [7:0]  vgaTextOutB;
wire        kbdDataRead;

reg  [7:0]  lastKbdByte;

//=======================================================
//  Structural coding
//=======================================================

/*
reg counter;
always @(posedge CLOCK_50 or posedge rst) begin
    if (rst) begin
        counter <= 0;
        clk <= 1'b0;
    end else begin
        counter <= counter + 1;
        if (counter == 0) begin
            clk <= ~clk;
        end
    end
end
*/

assign clk = CLOCK_50;
assign rst = SW[0];
assign LEDR[17:0] = imemAddr[17:0];
assign LEDG = {~rst, lastKbdByte};
assign PS2_CLK  = 1'bz;
assign PS2_DAT  = 1'bz;
assign PS2_CLK2 = 1'bz;
assign PS2_DAT2 = 1'bz;

always @(posedge clk or posedge rst) begin
    if (rst) begin
        lastKbdByte <= 8'h00;
    end else if (kbdDataRead) begin
        lastKbdByte <= dmemKbdOut[7:0];
    end
end

//=======================================================
//  Core
//=======================================================

CORE my_core(
    clk,
    rst,
    imemDataOut,
    dmemDataOut,
    imemAddr,
    dmemAddr,
    dmemDataIn,
    dmemOp,
    dmemWe,
    HEX0,
    HEX1,
    HEX2,
    HEX3,
    HEX4,
    HEX5,
    HEX6,
    HEX7
);

LCD_DRIVER lcd_driver(
    clk,
    rst,
    dmemAddr,
    dmemDataIn,
    dmemOp,
    dmemWe,
    dmemLcdOut,
    dmemLcdHit,
    LCD_DATA,
    LCD_BLON,
    LCD_EN,
    LCD_ON,
    LCD_RS,
    LCD_RW
);

PS2_KEYBOARD_DRIVER keyboard_driver(
    clk,
    rst,
    dmemAddr,
    dmemDataIn,
    dmemOp,
    dmemWe,
    PS2_CLK,
    PS2_DAT,
    dmemKbdOut,
    dmemKbdHit
);

VGA_DRIVER vga_driver(
    clk,
    rst,
    dmemAddr,
    dmemDataIn,
    dmemOp,
    dmemWe,
    vgaTextOutB,
    dmemVgaOut,
    dmemVgaHit,
    vgaTextAddrB,
    VGA_R,
    VGA_G,
    VGA_B,
    VGA_BLANK_N,
    VGA_CLK,
    VGA_HS,
    VGA_SYNC_N,
    VGA_VS
);

//=======================================================
//  Data memory adapter
//=======================================================

rv32i_data_mem_adapter dmem_adapter (
    .core_addr(dmemAddr),
    .core_wdata(dmemDataIn),
    .core_op(dmemOp),
    .core_we(dmemWe),
    .core_rdata(dmemRamOut),

    .ram_rdaddress(dmemRdAddr),
    .ram_wraddress(dmemWrAddr),
    .ram_wdata(dmemRamIn),
    .ram_byteena(dmemByteEn),
    .ram_wren(dmemRamWe),
    .ram_rdata(dmemRawOut)
);

assign dmemVgaTextHit = dmemAddr[31] && (dmemAddr[31:12] == 20'h80001);
assign kbdDataRead = dmemKbdHit && !dmemWe && (dmemAddr == 32'h80000084);
assign dmemVgaTextOut = (dmemOp == 3'b000) ? {{24{vgaTextOutA[7]}}, vgaTextOutA} :
                        {24'b0, vgaTextOutA};
assign dmemMmioHit = dmemLcdHit | dmemKbdHit | dmemVgaHit | dmemVgaTextHit;
assign dmemMmioOut = dmemLcdHit ? dmemLcdOut :
                     (dmemKbdHit ? dmemKbdOut :
                     (dmemVgaHit ? dmemVgaOut : dmemVgaTextOut));
assign dmemDataOut = dmemMmioHit ? dmemMmioOut : dmemRamOut;

assign vgaTextWe = dmemVgaTextHit && dmemWe;
assign vgaTextAddrA = dmemAddr[11:0];
assign vgaTextInA = dmemDataIn[7:0];

//=======================================================
//  Memories
//=======================================================

ram_a data_mem(
    .byteena_a(dmemByteEn),
    .data(dmemRamIn),
    .rdaddress(dmemRdAddr),
    .rdclock(~clk),
    .wraddress(dmemWrAddr),
    .wrclock(~clk),
    .wren(dmemRamWe && !dmemMmioHit),
    .q(dmemRawOut)
);

ram_b instr_mem(
    .address(imemAddr[16:2]),
    .clock(~clk),
    .data(32'b0),
    .wren(1'b0),
    .q(imemDataOut)
);

ram_c gfx_mem(
    .address_a(vgaTextAddrA),
    .address_b(vgaTextAddrB),
    .clock(clk),
    .data_a(vgaTextInA),
    .data_b(8'b0),
    .wren_a(vgaTextWe),
    .wren_b(1'b0),
    .q_a(vgaTextOutA),
    .q_b(vgaTextOutB)
);

endmodule

module rv32i_data_mem_adapter (
    input  wire [31:0] core_addr,
    input  wire [31:0] core_wdata,
    input  wire [2:0]  core_op,
    input  wire        core_we,
    output reg  [31:0] core_rdata,

    output wire [14:0] ram_rdaddress,
    output wire [14:0] ram_wraddress,
    output reg  [31:0] ram_wdata,
    output reg  [3:0]  ram_byteena,
    output wire        ram_wren,
    input  wire [31:0] ram_rdata
);

    wire [1:0] byte_offset = core_addr[1:0];
    wire       half_upper  = core_addr[1];
    wire [7:0]  load_byte = (ram_rdata >> ({byte_offset, 3'b000})) & 32'h000000ff;
    wire [15:0] load_half = half_upper ? ram_rdata[31:16] : ram_rdata[15:0];

    assign ram_rdaddress = core_addr[16:2];
    assign ram_wraddress = core_addr[16:2];
    assign ram_wren      = core_we;

    always @(*) begin
        ram_byteena = 4'b0000;
        ram_wdata   = 32'b0;

        case (core_op)
            3'b000, // sb / lb
            3'b100: begin // lbu
                ram_byteena = 4'b0001 << byte_offset;
                ram_wdata   = {24'b0, core_wdata[7:0]} << ({byte_offset, 3'b000});
            end

            3'b001, // sh / lh
            3'b101: begin // lhu
                ram_byteena = half_upper ? 4'b1100 : 4'b0011;
                ram_wdata   = half_upper ? {core_wdata[15:0], 16'b0} : {16'b0, core_wdata[15:0]};
            end

            3'b010: begin // sw / lw
                ram_byteena = 4'b1111;
                ram_wdata   = core_wdata;
            end

            default: begin
                ram_byteena = 4'b0000;
                ram_wdata   = 32'b0;
            end
        endcase
    end

    always @(*) begin
        case (core_op)
            3'b000: core_rdata = {{24{load_byte[7]}}, load_byte};
            3'b001: core_rdata = {{16{load_half[15]}}, load_half};
            3'b010: core_rdata = ram_rdata;
            3'b100: core_rdata = {24'b0, load_byte};
            3'b101: core_rdata = {16'b0, load_half};
            default: core_rdata = ram_rdata;
        endcase
    end
endmodule
